version=0.1

[default.package.paramaters]
s3_bucket="s3-snowflake-test-demo"
stack_name="lambda-stack"
region="ap-southeast-2"
capabilities="CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = """
  RawBucketName=raw-demo-test
  StagingBucketName=staging-demo-test
  Hl7ToJsonFunctionName=-hl7tojson-lambda
  LibraryBucketName=library-demo-test
  LibraryKey=hl7apy.zip

